## Constructeurs

In [2]:
import numpy as np

In [3]:
A = np.array([1,2,3])
A.ndim
A.shape

(3,)

In [4]:
# un tableau de zeros
B = np.zeros((3,2))
type(B.shape)

tuple

In [5]:
c = np.ones((3,4))
c.size

12

In [6]:
D = np.full((2,3),9)
D

array([[9, 9, 9],
       [9, 9, 9]])

In [7]:
#nombres aleatoires issus d'une distribution normale centrée
np.random.seed(0)
np.random.randn(3,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [8]:
#matrice d'identité
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
#tableau à une dimension dans lequel on va préciser valleun nombre de debut de fin et combien de nombres dans cet inter
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [10]:
#tableau à une dimension dans lequel on va préciser le debut fin et le pas
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
#préciser le type de données que l'on veut
np.linspace(0,20,10,dtype=np.float16)

array([ 0.   ,  2.223,  4.445,  6.668,  8.89 , 11.11 , 13.336, 15.555,
       17.78 , 20.   ], dtype=float16)

## Manipulation

In [12]:
A = np.zeros((3,2))
B = np.ones((3,2))

In [13]:
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [14]:
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
#methode hstack et vstack
c= np.hstack((A,B))

In [16]:
D = np.vstack((A,B))
D.shape

(6, 2)

In [17]:
np.concatenate((A,B), axis = 0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.concatenate((A,B), axis = 1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [19]:
# methode reshape
D = D.reshape((3,4))
D

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# très utile pour les tableau à 1 dimension car peut poser pbl dans certains algo
A = np.array([1,2,3])
A = A.reshape((A.shape[0],1))
A.shape

(3, 1)

In [21]:
#pour revenir à la shape de base
A = A.squeeze()

In [22]:
A.shape

(3,)

In [23]:
#methode ravel() applatit les tableaux peut être utile parfois
D.ravel().shape



(12,)

In [42]:
def initialisation(m,n):
    A = np.random.randn(m,n)
    
    B = np.ones((m,1))
    C = np.concatenate((A,B),axis = 1)
    
    
    return C

In [43]:
initialisation(3,2)

array([[-1.61389785, -0.21274028,  1.        ],
       [-0.89546656,  0.3869025 ,  1.        ],
       [-0.51080514, -1.18063218,  1.        ]])